# Generated by Django 6.1 on 2026-08-24 08:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('notes', models.CharField(blank=True, help_text='Optional reference or packing instructions.', max_length=255, verbose_name='Staff Notes')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Unique Stock Keeping Unit identifier.', max_length=64, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('length', models.DecimalField(decimal_places=2, help_text='Rigid bounding length in centimeters.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Length (cm)')),
                ('width', models.DecimalField(decimal_places=2, help_text='Rigid bounding width in centimeters.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Width (cm)')),
                ('height', models.DecimalField(decimal_places=2, help_text='Rigid bounding height in centimeters.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Height (cm)')),
                ('weight', models.DecimalField(decimal_places=3, help_text='Product unit weight in kilograms.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Weight (kg)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is available for order fulfillment.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='ShippingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique identifier or descriptive name (e.g. 'Box 1 - Small Mailer').", max_length=128, unique=True, verbose_name='Box Name')),
                ('length', models.DecimalField(decimal_places=2, help_text='Internal usable length in centimeters.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Internal Length (cm)')),
                ('width', models.DecimalField(decimal_places=2, help_text='Internal usable width in centimeters.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Internal Width (cm)')),
                ('height', models.DecimalField(decimal_places=2, help_text='Internal usable height in centimeters.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Internal Height (cm)')),
                ('max_weight', models.DecimalField(decimal_places=3, help_text='Maximum payload weight the box can physically support.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Max Weight Capacity (kg)')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost per box unit in dollars.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Cost ($)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this box is currently available for packaging recommendations.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Shipping Box',
                'verbose_name_plural': 'Shipping Boxes',
                'ordering': ['cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='warehouse.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['id'],
            },
        ),
    ]
